initialize
watchall
set r.g.Reset 0
set r.addressOne[0] 1
set r.addressOne[1] 0
set r.first.x[0] 0
set r.first.x[1] 0
set r.first.x[2] 0
set r.first.x[3] 1
set r.first.readyhuh 1
set r.first.flag[0] 0
set r.first.flag[1] 1
set r.addressTwo[0] 0
set r.addressTwo[1] 1
set r.second.x[0] 0
set r.second.x[1] 0
set r.second.x[2] 1
set r.second.x[3] 0
set r.second.readyhuh 1
set r.second.flag[0] 0
set r.second.flag[1] 1
set r.inTwo.b[0].t 1
set r.inTwo.b[0].f 0
set r.inTwo.b[1].t 1
set r.inTwo.b[0].f 0
set r.inTwo.b[0].t 0
set r.inTwo.b[2].f 1
set r.inTwo.b[3].t 1
set r.inTwo.b[0].f 0
set r.addressThree[0] 1
set r.addressThree[1] 1
set r.third.x[0] 0
set r.third.x[1] 0
set r.third.x[2] 1
set r.third.x[3] 1
set r.third.readyhuh 1
set r.third.flag[0] 0
set r.third.flag[1] 1
set r.cw.r 1
set r.cx.r 1
set r.cy.r 1
set r.cw.a 0
set r.cx.a 0
set r.cy.a 0
set r.w.e 0
set r.x.e 0
set r.y.e 0
set r.third.i.e 1
set r.third.o.e 1
set r.second.i.e 1
set r.second.o.e 1
set r.first.i.e 1
set r.first.o.e 1
cycle
set p.g.Reset 0
set p.r.e 1
cycle
set p.l.t 1
cycle
set p.r.e 0
cycle
set p.l.t 0
set p.l.f 0
cycle
initialize
watchall
random
set p.g.Reset 0
set p.r.e 1
cycle
set p.l.t 1
cycle
set p.r.e 0
cycle
set p.l.t 0
set p.l.f 0
cycle